process_names:
  - name: '{{.ExeBase}}:{{.Matches.jarname}}'
    exe:
    - java
    cmdline:
    - -classpath\s+(?P<jarname>\S*?.jar)

  - name: '{{.ExeBase}}:{{.Matches.jarname}}'
    exe:
    - java
    cmdline:
    - -cp\s+\S*?(?P<jarname>[^:]*?\.jar)

  - name: '{{.ExeBase}}:{{.Matches.config}}'
    exe:
    - /usr/local/scribe/bin/zingscribe
    cmdline:
    - (?P<config>[^/]+\.conf)

  - name: '{{.ExeBase}}:{{.Matches.config}}'
    exe:
    - /etc/scribe/bin/scribed
    cmdline:
    - (?P<config>[^/]+\.conf)
